language: generic
sudo: required

services:
 - docker:

before_install:
 - docker build -f -t shanu9/new docker.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test -- --coverage
